const emails = [
    {
        id: 1,
        category: "coworker",
        sender: "Marcus Aurelius",
        role: "Director of Marketing",
        badge: "Marketing",
        badgeClass: "badge-marketing",
        subject: "Finalizing the Q4 Strategy Document",
        time: "10:42 AM",
        fullTime: "London, UK • 10:42 AM",
        email: "marcus.a@editorial-workspace.com",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuD23x6sxf2mZqn1_ajz5z_I6LhZjy-EKIwAppXx3EkPOKyTlJR0GwRgjh9BfhVzaKe5yRQBRPSldUdaU1ygz6SNnKJzPCnyldQU5_wisBnURt0aJXWwkDp5RoOTCBogjre2AAYQr-njldTNMwrJBFT6GPQuiNKXSyUqGxc1zCofHid5wQYnjM16ZyeMGTXil1lZn9v-LMUSPU6kawb9FDEtHyE6Nw5KCXQ_AnWLZmTAR9aj7faVYCQrVDvcYkSk3u3QKPrMG5HE0FVo",
        largeAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAZZv8wqVwF5p9nuPLguU4R9eDgr5F6teQ8khEaJh9gpCHi0nbT0D8L4mTc4_J2sUVty0-gikV-vxW-CS-ui13Kp_d195FXqbv4M52jdDhQxUYWbw5SKaE4m6LALx_99zN3HnOwE0hepOh6S-xXFBTAfkSVxj9jiA1AKKl-5PfGJq3wDcUUU3MoS3Y-udakzqDedc5TQDhkihcZG77ul0WecHwPyjt2e4WtBDUSBx3eDplxo6_X1kzrKIxvHAOgM70dMxhc--GwM1ET",
        content: `<p>Hi Team,</p><p>I’ve just finished a walkthrough of the latest projections for the final quarter. As we move into the execution phase, I’d like to focus our discussion on two critical pillars: <strong>budget allocation</strong> across our digital channels and the overall <strong>creative direction</strong> for the holiday campaign.</p><div class="msg-callout"><h4 class="msg-callout-title"><span class="material-symbols-outlined" data-icon="info">info</span>Strategic Priority</h4><p class="msg-callout-text">"We need to ensure the messaging resonates with our core audience's shift toward sustainability while maintaining the premium editorial feel that defines our brand."</p></div><p>The attached PDF contains the updated V2 deck. Please review the slides regarding the paid media split. I’ve increased the weighting towards video storytelling, as our engagement metrics indicate a significant uplift in that area over the last 30 days.</p><p>Let’s aim to finalize these numbers by end of day Thursday so we can brief the creative studio on Friday morning.</p><p class="msg-signature">Best regards,<br /><span style="font-weight: 700; color: var(--primary);">Marcus Aurelius</span><br /><span style="font-size: 0.875rem; color: var(--on-surface-variant);">Director of Marketing &amp; Creative</span></p>`,
        snippet: "I've attached the latest drafts for the creative direction. We need to review the budget allocation for the social media campaigns before the...",
        hasAttachment: true,
        attachmentIcon: "picture_as_pdf",
        attachmentName: "Strategy_Deck_V2.pdf",
        attachmentMeta: "4.2 MB • Updated 2h ago",
        tags: ["Q4 Strategy", "Budget", "Marketing", "Urgent"],
        reminder: "Review deadline is Thursday, Oct 24, 5:00 PM.",
        unread: true
    },
    {
        id: 2,
        category: "coworker",
        sender: "Sarah Lansing",
        role: "HR Manager",
        badge: "Human Resources",
        badgeClass: "badge-hr",
        subject: "Quarterly Performance Review Schedule",
        time: "Yesterday, 4:20 PM",
        fullTime: "New York, US • Yesterday",
        email: "sarah.l@editorial-workspace.com",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAO9QlISuTz-44RtbjwMYK-CN0bPoQgG4bvVrHLDqul5a2QpKNMMDySzW0-vm3jCbcYEvJeADg3haa4sckUra9ifaC4KrimcbAONTH_-J-WRp9F5oElpiLs7l7TT1e1eTMzyoYUtDuwaZV_IBIClfhVZ4XiIGYUVjO32maSRdPRTIP52ZoIzp-jOuOHYrHuzIAD4tnxcYhecuTVGhyVd8ztYLZyNsPcrZne9CDWeGju_LfKf1R1rDB2L8XvEQxJmYXsF2pcBSUUo94k",
        largeAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAO9QlISuTz-44RtbjwMYK-CN0bPoQgG4bvVrHLDqul5a2QpKNMMDySzW0-vm3jCbcYEvJeADg3haa4sckUra9ifaC4KrimcbAONTH_-J-WRp9F5oElpiLs7l7TT1e1eTMzyoYUtDuwaZV_IBIClfhVZ4XiIGYUVjO32maSRdPRTIP52ZoIzp-jOuOHYrHuzIAD4tnxcYhecuTVGhyVd8ztYLZyNsPcrZne9CDWeGju_LfKf1R1rDB2L8XvEQxJmYXsF2pcBSUUo94k",
        content: `<p>Hi everyone,</p><p>Please make sure you've filled out your self-assessment forms by the end of the week. Link is in the portal under employees. We want to make sure everyone has enough time to address their goals and accomplishments from the last quarter before we set up individual 1-on-1s.</p><p class="msg-signature">Thanks,<br /><span style="font-weight: 700; color: var(--primary);">Sarah Lansing</span><br /></p>`,
        snippet: "Hi everyone, please make sure you've filled out your self-assessment forms by the end of the week. Link is in the portal under employees...",
        hasAttachment: false,
        tags: ["HR", "Reviews", "Mandatory"],
        reminder: "Self-assessment due this Friday.",
        unread: false
    },
    {
        id: 3,
        category: "coworker",
        sender: "David Kim",
        role: "Lead Engineer",
        badge: "Engineering",
        badgeClass: "badge-eng",
        subject: "Security patch deployed to staging",
        time: "Oct 24",
        fullTime: "San Francisco, US • Oct 24",
        email: "david.k@editorial-workspace.com",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxTODB3vbEHrtscLkbI2-NCsZjazqmxzL-Vzh9P3HQSXmcvCYDSFUiDpM_58DM4RkmzxUKi0Bcl78eY1SNZIu1JXClehKIiVlC39oI1xwFI7ID21b56hUe38I_nIRLjyme-QERJmv8RoRERBAxUMhyLEyYuZNNV2mdRKppX7ndZPc-mzbR7iBuJUepUL7Edo-qLbJTC_VQXqpf7dmXnd8KeRQDARxXiqHuYVix16D3Eyg3b0bfOOFa6BAqXRRmTMBntdOgoJIBalJD",
        largeAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxTODB3vbEHrtscLkbI2-NCsZjazqmxzL-Vzh9P3HQSXmcvCYDSFUiDpM_58DM4RkmzxUKi0Bcl78eY1SNZIu1JXClehKIiVlC39oI1xwFI7ID21b56hUe38I_nIRLjyme-QERJmv8RoRERBAxUMhyLEyYuZNNV2mdRKppX7ndZPc-mzbR7iBuJUepUL7Edo-qLbJTC_VQXqpf7dmXnd8KeRQDARxXiqHuYVix16D3Eyg3b0bfOOFa6BAqXRRmTMBntdOgoJIBalJD",
        content: `<p>Team,</p><p>The critical vulnerability identified in the auth module has been addressed. Please test your respective modules in the staging environment before midnight. The deployment to production is planned for tomorrow morning.</p><div class="msg-callout" style="background-color: rgba(250, 116, 111, 0.1); border-left-color: var(--error);"><h4 class="msg-callout-title" style="color: var(--error);"><span class="material-symbols-outlined" data-icon="warning">warning</span>Critical Priority</h4><p class="msg-callout-text" style="color: #6e0a12;">"Any modules failing tests in staging will delay the production release."</p></div><p class="msg-signature">Best,<br /><span style="font-weight: 700; color: var(--primary);">David Kim</span><br /></p>`,
        snippet: "The critical vulnerability identified in the auth module has been addressed. Please test your respective modules in the staging environment before midnight.",
        hasAttachment: false,
        tags: ["Security", "Staging", "Deployment", "Urgent"],
        reminder: "Test staging environment by midnight.",
        unread: true,
        priority: true
    },
    {
        id: 4,
        category: "coworker",
        sender: "Jane Thompson",
        role: "Head of Operations",
        badge: "Operations",
        badgeClass: "badge-ops",
        subject: "Office renovation update for next week",
        time: "Oct 23",
        fullTime: "London, UK • Oct 23",
        email: "jane.t@editorial-workspace.com",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBgW0f9gVDGOMZiis5aC8ND4ibh2PG8DqvI2fQGSpD6Irka1BfQx3o-N80Y_hMjX6DEMUOGLjQjYoHhKDkHa1rYZ7PgbSalz3Oe_dh3HIxW1Uv4FqRRy7ZogM5bOkvJnNb8nGDjwQ_V139kPnupUxG0U2Xp7o_ZDEr3z6Cd0BH2mWfQNjjmo0-fZx2ENp9fg4eHrpRtTBbA67VeB28qJ5wxzXDQmEdAOruuTCKqEnOrrol1vBdoRcYKk3CNQjD2oMFiCZiXbjvhAhTJ",
        largeAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBgW0f9gVDGOMZiis5aC8ND4ibh2PG8DqvI2fQGSpD6Irka1BfQx3o-N80Y_hMjX6DEMUOGLjQjYoHhKDkHa1rYZ7PgbSalz3Oe_dh3HIxW1Uv4FqRRy7ZogM5bOkvJnNb8nGDjwQ_V139kPnupUxG0U2Xp7o_ZDEr3z6Cd0BH2mWfQNjjmo0-fZx2ENp9fg4eHrpRtTBbA67VeB28qJ5wxzXDQmEdAOruuTCKqEnOrrol1vBdoRcYKk3CNQjD2oMFiCZiXbjvhAhTJ",
        content: `<p>Hello,</p><p>Floor 4 will be partially inaccessible starting Monday morning due to the new layout plan implementation. Please check the seating plan attached to see where your temporary workstation will be located during the week.</p><p class="msg-signature">Thanks for your patience,<br /><span style="font-weight: 700; color: var(--primary);">Jane Thompson</span><br /></p>`,
        snippet: "Floor 4 will be partially inaccessible starting Monday morning. Please check the seating plan attached to see where your temporary workstation will be located.",
        hasAttachment: true,
        attachmentIcon: "map",
        attachmentName: "Seating_Plan_Floor4.pdf",
        attachmentMeta: "1.8 MB",
        tags: ["Operations", "Office", "Facilities"],
        reminder: "Check temporary workstation assignment.",
        unread: false
    },
    // New ones:
    {
        id: 5,
        category: "external",
        sender: "TechSupply Co.",
        role: "B2B Vendor",
        badge: "Vendor",
        badgeClass: "badge-marketing", // Reusing styling
        subject: "Invoice #98234 for Q3 Equipment",
        time: "Oct 21",
        fullTime: "Seattle, US • Oct 21",
        email: "billing@techsupply.co",
        avatar: "https://ui-avatars.com/api/?name=Tech+Supply&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Tech+Supply&background=random",
        content: `<p>Dear customer,</p><p>Attached is the latest invoice for your recent hardware order. Please remit payment within the next 30 days to avoid late fees.</p><p class="msg-signature">Thank you,<br /><span style="font-weight: 700; color: var(--primary);">TechSupply Billing Team</span><br /></p>`,
        snippet: "Attached is the latest invoice for your recent hardware order. Please remit payment within the next 30 days to avoid late fees.",
        hasAttachment: true,
        attachmentIcon: "picture_as_pdf",
        attachmentName: "Invoice_98234.pdf",
        attachmentMeta: "250 KB",
        tags: ["Billing", "Hardware"],
        unread: false
    },
    {
        id: 6,
        category: "external",
        sender: "Creative Agency X",
        role: "Design Partner",
        badge: "Partner",
        badgeClass: "badge-ops",
        subject: "Asset Delivery: New Logo Variants",
        time: "Oct 20",
        fullTime: "Berlin, DE • Oct 20",
        email: "assets@agencyx.com",
        avatar: "https://ui-avatars.com/api/?name=Agency+X&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Agency+X&background=random",
        content: `<p>Hi team,</p><p>We have finalized the logo variants based on your latest feedback. The ZIP file contains EPS, PNG, and SVG formats, properly grouped and labeled.</p><p class="msg-signature">Best,<br /><span style="font-weight: 700; color: var(--primary);">Creative Agency X</span><br /></p>`,
        snippet: "We have finalized the logo variants based on your latest feedback. The ZIP file contains EPS, PNG, and SVG formats...",
        hasAttachment: true,
        attachmentIcon: "folder_zip",
        attachmentName: "Logo_Variants_Final.zip",
        attachmentMeta: "15.4 MB",
        tags: ["Design", "Assets"],
        unread: false
    },
    {
        id: 7,
        category: "external",
        sender: "CloudHost Inc.",
        role: "Cloud Provider",
        badge: "Service",
        badgeClass: "badge-eng",
        subject: "Scheduled Maintenance Notification",
        time: "Oct 18",
        fullTime: "Austin, US • Oct 18",
        email: "support@cloudhost.inc",
        avatar: "https://ui-avatars.com/api/?name=Cloud+Host&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Cloud+Host&background=random",
        content: `<p>Hello,</p><p>We will be performing scheduled network maintenance on our core routers this Sunday between 2:00 AM and 4:00 AM UTC. You might experience minor packet loss during this window.</p><p class="msg-signature"><span style="font-weight: 700; color: var(--primary);">CloudHost Support</span></p>`,
        snippet: "We will be performing scheduled network maintenance on our core routers this Sunday between 2:00 AM and 4:00 AM UTC...",
        hasAttachment: false,
        tags: ["IT", "Maintenance"],
        unread: true
    },
    {
        id: 8,
        category: "external",
        sender: "Office Direct",
        role: "Supplier",
        badge: "Supplier",
        badgeClass: "badge-hr",
        subject: "Your order #8821 has been shipped",
        time: "Oct 17",
        fullTime: "London, UK • Oct 17",
        email: "shipping@officedirect.com",
        avatar: "https://ui-avatars.com/api/?name=Office+Direct&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Office+Direct&background=random",
        content: `<p>Your recent order containing 5 ergonomic chairs and 3 monitor stands has been shipped via standard delivery. Expect it by Thursday.</p><p class="msg-signature"><span style="font-weight: 700; color: var(--primary);">Office Direct Logistics</span></p>`,
        snippet: "Your recent order containing 5 ergonomic chairs and 3 monitor stands has been shipped via standard delivery...",
        hasAttachment: false,
        tags: ["Office", "Delivery"],
        unread: false
    },
    {
        id: 9,
        category: "spam",
        sender: "Unknown Sender",
        role: "Unknown",
        badge: "Security Warning",
        badgeClass: "badge-hr",
        subject: "Urgent: Account Verification Required",
        time: "Oct 16",
        fullTime: "Unknown • Oct 16",
        email: "nobody@scam.site",
        avatar: "https://ui-avatars.com/api/?name=Unknown&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Unknown&background=random",
        content: `<p>Dear User,</p><p>Your workspace account access will be suspended in 24 hours if you do not view the attached document and provide your recent login details.</p><p>Do NOT ignore this message!</p>`,
        snippet: "Your workspace account access will be suspended in 24 hours if you do not view the attached document...",
        hasAttachment: true,
        attachmentIcon: "description",
        attachmentName: "Account_Verification.pdf",
        attachmentMeta: "10 KB",
        tags: ["Suspected Spam", "Phishing"],
        unread: false,
        priority: true
    },
    {
        id: 10,
        category: "spam",
        sender: "John Doe",
        role: "Applicant",
        badge: "External",
        badgeClass: "badge-marketing",
        subject: "Application for Editor Position",
        time: "Oct 15",
        fullTime: "Toronto, CA • Oct 15",
        email: "johndoe1998@email.com",
        avatar: "https://ui-avatars.com/api/?name=John+Doe&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=John+Doe&background=random",
        content: `<p>To Whom it May Concern,</p><p>I am reaching out to submit my resume for the open editor position I saw on your career site. I have over 5 years of editorial experience and a keen eye for detail.</p><p>Please find my resume attached.</p><p class="msg-signature">Best,<br /><span style="font-weight: 700; color: var(--primary);">John Doe</span></p>`,
        snippet: "I am reaching out to submit my resume for the open editor position I saw on your career site...",
        hasAttachment: true,
        attachmentIcon: "contact_page",
        attachmentName: "Resume_John_Doe.pdf",
        attachmentMeta: "1.2 MB",
        tags: ["Recruitment", "Resume"],
        unread: true
    },
    {
        id: 11,
        category: "spam",
        sender: "Weekly Tech Digest",
        role: "Newsletter",
        badge: "Newsletter",
        badgeClass: "badge-ops",
        subject: "Your Weekly Tech Insights",
        time: "Oct 14",
        fullTime: "Global • Oct 14",
        email: "newsletter@techdigest.io",
        avatar: "https://ui-avatars.com/api/?name=Tech+Digest&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=Tech+Digest&background=random",
        content: `<p>Hello reader!</p><p>This week we cover the latest advancements in web architecture, the new styling trends, and deep dive into vanilla CSS best practices.</p><p>Check the attached digest for full articles.</p><p class="msg-signature">Cheers,<br /><span style="font-weight: 700; color: var(--primary);">The Digest Team</span></p>`,
        snippet: "This week we cover the latest advancements in web architecture, the new styling trends, and deep dive into vanilla CSS...",
        hasAttachment: true,
        attachmentIcon: "picture_as_pdf",
        attachmentName: "Digest_Oct_Week3.pdf",
        attachmentMeta: "3.5 MB",
        tags: ["Newsletter", "Tech"],
        unread: false
    },
    {
        id: 12,
        category: "spam",
        sender: "Prince Al-Waleed",
        role: "Investor",
        badge: "Spam",
        badgeClass: "badge-hr",
        subject: "Business Proposal - Confidential",
        time: "Oct 13",
        fullTime: "Unknown • Oct 13",
        email: "biz_proposal@royalnet.com",
        avatar: "https://ui-avatars.com/api/?name=P+A&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=P+A&background=random",
        content: `<p>I have an urgent business proposal for you that guarantees $50 million. Please reply with your bank details immediately.</p>`,
        snippet: "I have an urgent business proposal for you that guarantees $50 million. Please reply with your bank details immediately.",
        hasAttachment: true,
        attachmentIcon: "description",
        attachmentName: "Proposal_Confidential.docx",
        attachmentMeta: "500 KB",
        tags: ["Spam", "Phishing"],
        unread: true
    },
    {
        id: 13,
        category: "spam",
        sender: "SEO Experts",
        role: "Agency",
        badge: "Promotion",
        badgeClass: "badge-marketing",
        subject: "Boost Your Website Traffic",
        time: "Oct 12",
        fullTime: "Remote • Oct 12",
        email: "sales@seoexperts.net",
        avatar: "https://ui-avatars.com/api/?name=SEO+E&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=SEO+E&background=random",
        content: `<p>Hi there,</p><p>Did you know your website is missing out on thousands of visitors? We can help you rank on page 1 of Google guaranteed!</p><p class="msg-signature">Reply to find out more.</p>`,
        snippet: "Did you know your website is missing out on thousands of visitors? We can help you rank on page 1 of Google guaranteed!",
        hasAttachment: false,
        tags: ["Promotion", "Marketing"],
        unread: false
    },
    {
        id: 14,
        category: "spam",
        sender: "Lottery Winners Inc.",
        role: "Promoter",
        badge: "Spam",
        badgeClass: "badge-hr",
        subject: "You have won $1,000,000!",
        time: "Oct 11",
        fullTime: "Unknown • Oct 11",
        email: "winner@lotteryscam.com",
        avatar: "https://ui-avatars.com/api/?name=L+W&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=L+W&background=random",
        content: `<p>Congratulations, your email address has been selected as the winner of our grand prize! Click here to claim your winnings.</p>`,
        snippet: "Congratulations, your email address has been selected as the winner of our grand prize! Click here to claim your winnings.",
        hasAttachment: false,
        tags: ["Spam", "Scam"],
        unread: false
    },
    {
        id: 15,
        category: "spam",
        sender: "HR Departament",
        role: "Administration",
        badge: "Urgent",
        badgeClass: "badge-hr",
        subject: "Immediate Action: Document Signature",
        time: "Oct 10",
        fullTime: "Unknown • Oct 10",
        email: "hr-update@external-portal.com",
        avatar: "https://ui-avatars.com/api/?name=HR+D&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=HR+D&background=random",
        content: `<p>Attention Employee,</p><p>You must review and sign the attached document to comply with our updated security policies before end of day. <a href="#" style="color: var(--primary); text-decoration: underline;">Click here to access the alternative portal</a> if you cannot open the attachment.</p>`,
        snippet: "You must review and sign the attached document to comply with our updated security policies before end of day...",
        hasAttachment: true,
        attachmentIcon: "description",
        attachmentName: "Policy_Update_v4.pdf",
        attachmentMeta: "2.1 MB",
        tags: ["Spam", "Phishing"],
        unread: true
    },
    {
        id: 16,
        category: "spam",
        sender: "IT Helpdesk",
        role: "Support Mask",
        badge: "Security",
        badgeClass: "badge-eng",
        subject: "Password Expiry Notice",
        time: "Oct 09",
        fullTime: "Unknown • Oct 09",
        email: "admin@it-helpddeskk.net",
        avatar: "https://ui-avatars.com/api/?name=IT+H&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=IT+H&background=random",
        content: `<p>Hello,</p><p>Your intranet portal password will expire in exactly 2 hours. To maintain access to your corporate emails and documents, please <a href="#" style="color: var(--primary); font-weight: bold; text-decoration: underline;">update your password here</a> immediately.</p>`,
        snippet: "Your intranet portal password will expire in exactly 2 hours. To maintain access to your corporate emails...",
        hasAttachment: false,
        tags: ["Spam", "Credential Theft"],
        unread: false,
        priority: true
    },
    {
        id: 17,
        category: "spam",
        sender: "Express Courier",
        role: "Delivery",
        badge: "Notification",
        badgeClass: "badge-ops",
        subject: "Failed Delivery Attempt",
        time: "Oct 08",
        fullTime: "Unknown • Oct 08",
        email: "tracking@express-courier-service.com",
        avatar: "https://ui-avatars.com/api/?name=E+C&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=E+C&background=random",
        content: `<p>We missed you!</p><p>A package addressed to you could not be delivered because no one was at the reception. Please download the attached shipping label and <a href="#" style="color: var(--primary); text-decoration: underline;">reschedule delivery online</a>.</p>`,
        snippet: "A package addressed to you could not be delivered because no one was at the reception...",
        hasAttachment: true,
        attachmentIcon: "folder_zip",
        attachmentName: "Shipping_Label_Print.zip",
        attachmentMeta: "540 KB",
        tags: ["Spam", "Malware"],
        unread: true
    },
    {
        id: 18,
        category: "spam",
        sender: "Bank Security",
        role: "Financial",
        badge: "Alert",
        badgeClass: "badge-marketing",
        subject: "Account Suspended: Fraud Activity",
        time: "Oct 08",
        fullTime: "Unknown • Oct 08",
        email: "alerts@corporatebank-secure.com",
        avatar: "https://ui-avatars.com/api/?name=B+S&background=random",
        largeAvatar: "https://ui-avatars.com/api/?name=B+S&background=random",
        content: `<p>Dear Customer,</p><p>We detected suspicious login attempts on your corporate card portal. Your card has been temporarily blocked. Please review the attached transaction statement and <a href="#" style="color: var(--primary); text-decoration: underline;">verify your identity to unblock</a> your account.</p>`,
        snippet: "We detected suspicious login attempts on your corporate card portal. Your card has been temporarily blocked...",
        hasAttachment: true,
        attachmentIcon: "picture_as_pdf",
        attachmentName: "Statement_Report.pdf",
        attachmentMeta: "1.4 MB",
        tags: ["Spam", "Phishing"],
        unread: false
    }
];
